### ISSUE TITLE
Questions do not fit in screen on mobile in list format

### ISSUE THREAD

**Issue by AustenLamacraft** [tripos-education/maths-tripos-questions#339]
Individual questions look good on mobile but in a list format they overrun. I assume there is some CSS to do to fix this

**Comment by thenewtonium** [comment]
I think the reason for this is that most lists have at least one question with block LaTeX that is too wide; e.g. on the [Coding and Cryptography](https://questions.tripos.org/courses/coding%20and%20cryptography/) page the question from [2020 Paper 1, Section II](https://questions.tripos.org/part-ii/2020-38/) is too wide even on its own page.

One solution could be to set the post contents to have `overflow-x: scroll` so that the overwide questions don't screw with the rest of the page, but have it sill possible to see the whole question?
